
create database demo3;

use demo3;

-- 카테고리 테이블 (상위, 하위 개념 추가)
create table tb_categories(
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID INT NULL,
    CATEGORY_NAME VARCHAR(100),	
    FOREIGN KEY(PARENT_ID) REFERENCES TB_CATEGORIES(CATEGORY_ID)
);

INSERT INTO TB_CATEGORIES(CATEGORY_NAME) VALUES('남성복');
INSERT INTO TB_CATEGORIES(CATEGORY_NAME) VALUES('여성복');

-- 남성복의 하위 카테고리
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('팬츠',1);    
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('셔츠',1);

-- 여성복의 하위 카테고리
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('팬츠',2);    
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('셔츠',2);
    
-- 남성복 팬츠의 하위 카테고리
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('면바지',3);
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('슬랙스',3);
    
-- 남성복 팬츠의 하위 카테고리
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('면바지',5);
INSERT INTO TB_CATEGORIES(CATEGORY_NAME,PARENT_ID) 
	VALUES('슬랙스',5);
    
SELECT*FROM tb_categorieS;